[package]
name = "unicode-cli"
version = "0.1.0"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]
edition = "2018"
description = "Unicode character lookup and inspection tool."

[dependencies]
unicode_names2 = "0.2.2"
clap = "2.33.0"
csv = "1.0.7"
unic-ucd = "0.9.0"
